"""made some changes in booking

Revision ID: 0313af5152bc
Revises: 3f378b8ff6a1
Create Date: 2025-06-30 00:27:58.763974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0313af5152bc'
down_revision = '3f378b8ff6a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_column('parking_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parking_date', sa.DATE(), nullable=False))

    # ### end Alembic commands ###
