"""made some changes in parking lot

Revision ID: f687ae16c6b6
Revises: 
Create Date: 2025-06-29 11:24:48.918415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f687ae16c6b6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parking_lot', schema=None) as batch_op:
        batch_op.add_column(sa.Column('occupied', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parking_lot', schema=None) as batch_op:
        batch_op.drop_column('occupied')

    # ### end Alembic commands ###
